# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0cbfd4ca754370186e4a0bfd4d528bd6bba45d4606e38afb10fb62bd33ebaa75ea5ef9bac0fe29caddfa66e8fc1a46d218acfdfbb4a36374326661a8df3425e

test:
  secret_key_base: be11fe0028277e8a49705bcc3c2f8b4b3e25c71eeae30dc74dd22e5e3befd0f8e6485f322d6bf6afbd6b393f7510334247ec17b50d8b29905acf5b2a3587a88b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
